config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public  do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/mypage/edit' => 'customers#edit'
    get '/customers/acitve_confirm' => 'customers#active_confirm'
    patch '/customers/mypage/update' => 'customers#update'
    patch '/customers/not_active' => 'customers#not_active'

    resources :orders do
     collection do
     post :confirm
     get :complete
     end
    end

    resources :addresses, only:[:index, :edit, :update, :destroy, :create]
    resources :items, only:[:show, :index]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    patch 'order_details/update'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    get '/products/search', to: 'products#search', as: 'search'
    resources :products, only:[:index, :new, :create, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.user_name = "Guest"
      customer.password = SecureRandom.urlsafe_base64
      customer.postal_code = "1111111"
      customer.address = "guest"
      customer.last_name = "Guest"
      customer.telephone_number = "11111111111"
      customer.first_name = "Guest"
      customer.last_name_kana = "ゲスト"
      customer.first_name_kana = "ゲスト"
      customer.is_active = true
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    custmoer = Customer.find(params[:id])
    custmoer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:user_name,:last_name, :first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_active,:email)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
      redirect_to new_customer_registration_path
    end
  end

  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
 <div class="container">
    <h1><%= @customer.last_name %><%= @customer.first_name %>の会員情報編集</h1>
    <div class="border-top border-dark" style="padding:5px;"></div><br>
    <div class="text-right">
    </div>
  <div>
  <%= form_with model:@customer, url:admin_customer_path(@customer.id), local:true do |f| %>
    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">ユーザー名</label>
      <%= f.text_field :user_name, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">姓</label>
      <%= f.text_field :last_name, class: "col-sm-10 form-control" %>
    </div>

     <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">名</label>
      <%= f.text_field :first_name, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">セイ</label>
      <%= f.text_field :last_name_kana, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">メイ</label>
      <%= f.text_field :first_name_kana, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">郵便番号</label></label>
      <%= f.text_field :postal_code, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">住所</label>
      <%= f.text_field :address, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">電話番号</label>
      <%= f.text_field :telephone_number, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">メールアドレス</label>
      <%= f.text_field :email, class: "col-sm-10 form-control" %>
    </div>

    <div class="mb-3 row">
      <label class="col-sm-2 col-form-label">会員ステータス</label>
      <div class="form-check">
        <%= f.radio_button :is_active, :true %>
        <label class="form-check-label"> 有効</label>
      </div>
      <div class="form-check">
        <%= f.radio_button :is_active, :false %>
        <label class="form-check-label"> 無効</label>
      </div>
    </div>


    <div class="form-group">
      <div class="text-right">
      <%= f.submit :"Save Changes", class: "btn btn-secondary" %>
      </div>
    </div>
  <% end %>
 </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h1>会員一覧</h1>

  <div class="border-top border-dark" style="padding:5px;"></div><br>
  <table class="table table-striped">
   <thead class="thead-dark">
    <tr>
     <th>会員ID</th>
     <th>氏名</th>
     <th>メールアドレス</th>
     <th>ステータス</th>
    </tr>
   </thead>
   <thody>
    <% @customers.each do |customer| %>
     <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.user_name, admin_customer_path(customer.id) %></td>
      <td><%= customer.email %></td>
      <td><%= customer.is_active %></td>
     </tr>
    <% end %>
    <%= paginate @customers %>
   </thody>
  </table>
</div>

app/views/admin/customers/show.html.erb
 <div class="container">
    <h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h1>
    <div class="border-top border-dark" style="padding:5px;"></div><br>
  <div>
  <table class="table table-striped">
   <thody>
     <tr>
      <td>会員ID</td>
      <td><%= @customer.id%></td>
     </tr>
     <tr>
      <td>氏名</td>
      <td><%= @customer.last_name%><%= @customer.first_name%></td>
     </tr>
     <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana%><%= @customer.first_name_kana%></td>
     </tr>
     <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code%></td>
     </tr>
     <tr>
      <td>住所</td>
      <td><%= @customer.address%></td>
     </tr>
     <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number%></td>
     </tr>
     <tr>
     <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email%></td>
     </tr>
     <tr>
      <td>会員ステータス</td>
      <td><%= @customer.is_active%></td>
     </tr>
    </thody>
   </table>
   <%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-secondary btn-sm" %>
   <%= link_to "注文履歴一覧を見る", admin_root_path(id: @customer.id), class:"btn btn-secondary btn-sm" %>
  </div>
 </div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>