config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public  do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/mypage/edit' => 'customers#edit'
    get '/customers/acitve_confirm' => 'customers#active_confirm'
    patch '/customers/mypage/update' => 'customers#update'
    patch '/customers/not_active' => 'customers#not_active'

    resources :orders do
     collection do
     post :confirm
     get :complete
     end
    end

    resources :addresses, only:[:index, :edit, :update, :destroy, :create]
    resources :items, only:[:show, :index]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    patch 'order_details/update'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    get '/products/search', to: 'products#search', as: 'search'
    resources :products, only:[:index, :new, :create, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code,:address,:customer_name,:shipping_fee,:payment_amount,:payment_method,:status, presence: true

  enum payment_method: {
  credit: 0,
  bank_transfar: 1,
  }

  enum status: {
    waiting: 0,
    paid_up: 1,
    processing: 2,
    preparing: 3,
    shipped: 4
  }

  def total_price
   self.item.price*self.amount
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
    @sum = 0
    @order_details.each do |order_detail|
     sub_total = order_detail.total_price.to_i
     @sum+=sub_total
    end

    if @order.payment_method == 0
     @payment_method = "クレジット"
    else
     @payment_method = "銀行振り込み"
    end
  end

  def update
    order = Order.find(params[:id])
    order.update(status: params[:order][:status])
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)

    @sum = 0
    @order_details.each do |order_detail|
      sub_total = order_detail.total_price.to_i
      @sum+=sub_total
     end
    render :show
  end

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h1>注文履歴詳細</h1>
  <div class="border-top border-dark" style="padding:5px;"></div><br>

  <div class="row">
    <div class="col-6">
    <table class="table table-bordered">
      <thody>
        <tr>
            <td class="bg-dark text-light">
            購入者
            </td>
            <td>
            <%= @order.customer.last_name %><%= @order.customer.first_name %>
            </td>
        </tr>
        <tr>
            <td class="bg-dark text-light">
            注文日
            </td>
            <td>
            <%= @order.created_at.strftime('%Y/%m/%d') %>
            </td>
        </tr>
        <tr>
            <td class="bg-dark text-light">
              配送先
            </td>
            <td>
              〒<%= @order.postal_code %>
              <%= @order.address %>
            </td>
        </tr>
        <tr>
            <td class="bg-dark text-light">
              支払い方法
            </td>
            <td>
            <%= @order.payment_method %>
            </td>
        </tr>
        <tr>
            <td class="bg-dark text-light">
              注文ステータス
            </td>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order), class:"form-horizontal", local:true do |f|%>
               <%= f.select :status, [['入金待ち','waiting'], ['入金確認', 'paid_up'],['制作中', 'preparing'],['発送準備中', 'shipped'],['発送済', 'shipped']], class:"form-control" %>
               <%= f.submit '更新', class:"btn btn-secondary btn-sm" %>
              <% end %>
            </td>
        </tr>
      </thody>
    </table>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
    <table  class="table table-bordered">
    <thead class="thead-dark">
        <tr>
          <th>
          　商品
          </th>
          <th>
            単価（税込）
          </th>
          <th>
            個数
          </th>
          <th>
            小計
          </th>
          <th>
            製造ステータス
          </th>
        </tr>
    </thead>
    <thody>
        <% sum = 0 %>
        <% @order_details.each do |order_detail|%>
        <tr>
          <td>
            <%= order_detail.item.name %>
          </td>
          <td>
            ¥ <%= add_tax_price = (order_detail.price*1.1).floor %>
          </td>
          <td>
            <%= amount = order_detail.amount %>
          </td>
          <td>
            ¥ <%= amount_money = add_tax_price*amount %>
          </td>
          <td>
            <div class="form-group">
             <%= form_with model:order_detail, url: admin_order_details_update_path(order_detail), class:"form-horizontal", local:true do |f|%>
              <%= f.select :is_active, [['製作不可','cant_be_produced'], ['製作待ち', 'wating_produce'],['製作中', 'producing'],['製作完了', 'produced']], class:"form-control" %>
              <%= f.hidden_field :id, :value => order_detail.id %>
              <%= f.hidden_field :order_id, :value => order_detail.order.id %>
             <%= f.submit '更新', class:"btn btn-secondary btn-sm" %>
             <% end %>
            </div>
          </td>
        </tr>
         <% sub_total = amount_money %>
         <% sum+=sub_total %>
        <% end %>
         <% @sum2 = sum %>
    </thody>
    </table>
    </div>

    <div class="col-4">
    <table class="table table-bordered">
      <thody>
        <tr>
          <td class="bg-dark text-light">
            商品合計
          </td>
          <td>
            ¥ <%= @sum %>
          </td>
        </tr>
        <tr>
          <td class="bg-dark text-light">
            送料
          </td>
          <td>
            ¥ <%= 800 %>
          </td>
        </tr>
        <tr>
          <td class="bg-dark text-light">
            請求金額合計
          </td>
          <td>
            ¥ <%= @sum + 800 %>
          </td>
        </tr>
        </thody>
    </table>
    </div>
  </div>

    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>