config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public  do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/mypage/edit' => 'customers#edit'
    get '/customers/acitve_confirm' => 'customers#active_confirm'
    patch '/customers/mypage/update' => 'customers#update'
    patch '/customers/not_active' => 'customers#not_active'

    resources :orders do
     collection do
     post :confirm
     get :complete
     end
    end

    resources :addresses, only:[:index, :edit, :update, :destroy, :create]
    resources :items, only:[:show, :index]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    patch 'order_details/update'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    get '/products/search', to: 'products#search', as: 'search'
    resources :products, only:[:index, :new, :create, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def search
    @items = Item.search(params[:search])
    puts "================"
     puts params[:page]
     puts "================"
    render :index
  end

  def index
    @items = Item.all
  end

  def new
    @new_item = Item.new
    @genres = Genre.all
  end

  def create
    @new_item = Item.new(item_params)
    if @new_item.save
      redirect_to admin_product_path(@new_item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_products_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :price, :introduction, :is_active)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
 <div class="container">
  <h1>商品編集</h1>
  <div class="border-top border-dark" style="padding:5px;"></div><br>

  <%= form_with model:@item, url:admin_product_path(@item.id), local:true do |f| %>
   <div class="form-group">
   <label>商品画像</label>
   <%= f.attachment_field :image%>
   </div>

   <div class="form-group">
   <label>商品名</label>
   <%= f.text_field :name, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>商品説明</label>
   <%= f.text_area :introduction, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>ジャンル</label>
   <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "選択して下さい", class:"form-control" %>
   </div>

   <div class="form-group">
   <label>税抜価格(円)</label>
   <%= f.text_field :price, class:"form-control" %>
   </div>

   <div class="form-group">
   <label>販売ステータス</label></br>
   販売中 <%= f.radio_button :is_active, :true %>
   販売停止中 <%= f.radio_button :is_active, :false %>
   </div>

   <%= f.submit '更新', class:"btn btn-secondary btn-md" %>

   <% end %>
 </div>

app/views/admin/products/index.html.erb
 <div class="container">
  <h1>商品一覧</h1>
  <div class="border-top border-dark" style="padding:5px;"></div><br>
  <div class="row"><%= link_to " 商品登録", new_admin_product_path, class:"btn btn-secondary btn-md" %>
  </div>
  <div class="text-right">
  <%= form_tag(admin_search_path,:method => 'get') do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'Search', :name => nil %>
  <% end %>
  </div>
  <div class="row">
  <table class="table table-striped">
   <thead class="thead-dark">
    <tr>
     <th>商品ID</th>
     <th>商品名</th>
     <th>税抜価格</th>
     <th>ジャンル</th>
     <th>ステータス</th>
    </tr>
   </thead>
   <thody>
    <% @items.each do |item| %>
     <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name,admin_product_path(item) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.genre_name %></td>
      <td><%= item.is_active %></td>
    </tr>
    <% end %>
   </thody>
  </table>
  </div>
</div>

app/views/admin/products/new.html.erb
 <div class="container">
  <h1>商品新規登録</h1>
  <div class="border-top border-dark" style="padding:5px;"></div><br>

  <%= form_with model:@new_item, url:admin_products_path, local:true do |f| %>
   <div class="form-group">
   <label>商品画像</label>
   <%= f.attachment_field :image%>
   </div>

   <div class="form-group">
   <label>商品名</label>
   <%= f.text_field :name, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>商品説明</label>
   <%= f.text_area :introduction, class:"form-control"  %>
   </div>

   <div class="form-group">
   <label>ジャンル</label>
   <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "選択して下さい", class:"form-control"  %>
   <!--なぜ@genresはだめなのか？-->
   </div>

   <div class="form-group">
   <label>税抜価格</label>
   <%= f.text_field :price, class:"form-control" %>
   </div>

   <div class="form-group">
   <label>販売ステータス</label></br>
   販売中 <%= f.radio_button :is_active, :true, checked: true %>
   販売停止中 <%= f.radio_button :is_active, :false %>
   </div>

   <%= f.submit '新規登録', class:"btn btn-secondary btn-md" %>
   <% end %>
 </div>

app/views/admin/products/show.html.erb
<div class="container">
  <h1>商品詳細</h1>
  <div class="border-top border-dark" style="padding:5px;"></div><br>

  <div class="row text-center">
    <div class="col-4">
    <%= attachment_image_tag @item, :image, size: "350x350", fallback: "no_image.jpg", size:'150x150' %>
    </div>
    <div class="col-6 text-left">
      <table >
       <tbody>
        <tr>
         <td style="width: 50%">商品名</td>
         <td style="width: 50%" ><%= @item.name %></td>
        </tr>
        <tr>
         <td>商品説明</td>
         <td><%= @item.introduction %></td>
        </tr>
        <tr>
         <td>ジャンル</td>
         <td><%= @item.genre.genre_name %></td>
        </tr>
        <tr>
         <td>税込価格</br>(税抜き価格)</td>
         <td>
          ¥ <% add_tax_price = @item.price*1.1 %>
          <%= add_tax_price.floor %>
          (¥ <%= @item.price %>)
         </td>
        </tr>
        <tr>
         <td>販売ステータス</td>
         <td><%= @item.is_active%></td>
        </tr>
       </tbody>
      </table>
    </div>
  </div>
  <div class="row">
   <div class="col text-center"><%= link_to '編集', edit_admin_product_path(@item.id), class:"btn btn-secondary btn-lg" %></div>
  </div>
</div>

app/views/admin/products/update.html.erb
<h1>Admin::Products#update</h1>
<p>Find me in app/views/admin/products/update.html.erb</p>