config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :customers, controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public  do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/mypage/edit' => 'customers#edit'
    get '/customers/acitve_confirm' => 'customers#active_confirm'
    patch '/customers/mypage/update' => 'customers#update'
    patch '/customers/not_active' => 'customers#not_active'

    resources :orders do
     collection do
     post :confirm
     get :complete
     end
    end

    resources :addresses, only:[:index, :edit, :update, :destroy, :create]
    resources :items, only:[:show, :index]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    patch 'order_details/update'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    get '/products/search', to: 'products#search', as: 'search'
    resources :products, only:[:index, :new, :create, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def total_price
   self.item.price*self.amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.user_name = "Guest"
      customer.password = SecureRandom.urlsafe_base64
      customer.postal_code = "1111111"
      customer.address = "guest"
      customer.last_name = "Guest"
      customer.telephone_number = "11111111111"
      customer.first_name = "Guest"
      customer.last_name_kana = "ゲスト"
      customer.first_name_kana = "ゲスト"
      customer.is_active = true
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  with_options presence: true do
  validates :genre_id
  validates :name
  validates :image
  validates :price
  validates :introduction
  validates :is_active
  end



  def self.search(search)
    return Item.all unless search
    Item.where(['name LIKE ?', "%#{search}%"])
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code,:address,:customer_name,:shipping_fee,:payment_amount,:payment_method,:status, presence: true

  enum payment_method: {
  credit: 0,
  bank_transfar: 1,
  }

  enum status: {
    waiting: 0,
    paid_up: 1,
    processing: 2,
    preparing: 3,
    shipped: 4
  }

  def total_price
   self.item.price*self.amount
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def total_price
   self.item.price*self.amount
  end

  enum status: {
    cant_be_produced: 0,
    wating_produce: 1,
    producing: 2,
    produced: 3
  }

end

app/models/rail.rb
class Rail < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @new_genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:genre_name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    if params[:id]
     @orders = Order.where(customer_id: params[:id])
    else
     @orders = Order.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   case resource
   when Admin
     admin_root_path
   when Customer
     root_path
   end
  end

  def after_sign_out_path_for(resource)
    if resource == :customer
      new_customer_session_path# ログアウト後に遷移するpathを設定
    else
      new_admin_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name,:last_name,:first_name,:last_name_kana,
    :first_name_kana,:email,:postal_code,:address,:telephone_number,:password,:password_confirmation, :is_active])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name,:last_name, :first_name,:last_name_kana,
    :first_name_kana,:postal_code,:address,:telephone_number,:is_active,:email,:encrypted_password,:password_confirmation])
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  # end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: "fas fa-birthday-cake navbar-brand nav-link text_light" do %><span> 永野CAKE</span>
          <% end %>

          <% if customer_signed_in? %>
            <div class="text-light">Welcome to <%= current_customer.user_name %> </div>
          <% end %>
          <div>
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
              <li><%= link_to "My Page", customers_mypage_path, class:"fas fa-user nav-link text_light"%></li>
              <li><%= link_to " Products", items_path, class:"fas fa-store nav-link text_light" %></li>
              <li><%= link_to " Cart", cart_items_path, class:"fas fa-info-circle nav-link text-light" %></li>
              <li><%= link_to " Log out", destroy_customer_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
              <% elsif admin_signed_in? %>
              <li><%= link_to " 商品一覧", admin_products_path, class:"nav-link text_light" %></li>
              <li><%= link_to " 会員一覧", admin_customers_path, class:"nav-link text-light" %></li>
              <li><%= link_to " 注文履歴一覧", admin_root_path, class:"nav-link text-light" %></li>
              <li><%= link_to " ジャンル一覧", admin_genres_path, class:"nav-link text-light" %></li>
              <li><%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link text-light" %></li>
              <% else %>
              <li><%= link_to " About", about_path, class:"fas fa-info-circle nav-link text-light" %></li>
              <li><%= link_to " Products", items_path, class:"fas fa-store nav-link text-light" %></li>
              <li><%= link_to " Sign Up", new_customer_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
              <li><%= link_to " Log in", new_customer_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <main>
      <%= yield %>
    </main>
    <footer style="background-color: #FFFF00;">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto"><p>CopyRight NaganoCake.inc</p></div>
        </div>
      </div>
    </footer>
  </body>
</html>